/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface DutchAuctionsInterface extends utils.Interface {
  functions: {
    "bid(uint256)": FunctionFragment;
    "erc20TokenAddress()": FunctionFragment;
    "erc721TokenAddress()": FunctionFragment;
    "finalize()": FunctionFragment;
    "getAddressOfOwner()": FunctionFragment;
    "getNounceValue()": FunctionFragment;
    "getNumBlocksOpen()": FunctionFragment;
    "getOfferPriceDecrement()": FunctionFragment;
    "getPrice()": FunctionFragment;
    "getReservePrice()": FunctionFragment;
    "getWinnerAddress()": FunctionFragment;
    "nftTokenId()": FunctionFragment;
    "nop()": FunctionFragment;
    "refund(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "bid"
      | "erc20TokenAddress"
      | "erc721TokenAddress"
      | "finalize"
      | "getAddressOfOwner"
      | "getNounceValue"
      | "getNumBlocksOpen"
      | "getOfferPriceDecrement"
      | "getPrice"
      | "getReservePrice"
      | "getWinnerAddress"
      | "nftTokenId"
      | "nop"
      | "refund"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "bid",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "erc20TokenAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "erc721TokenAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "finalize", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAddressOfOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getNounceValue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getNumBlocksOpen",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOfferPriceDecrement",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getPrice", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getReservePrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getWinnerAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nftTokenId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "nop", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "refund",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(functionFragment: "bid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "erc20TokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "erc721TokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "finalize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAddressOfOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNounceValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNumBlocksOpen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOfferPriceDecrement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getReservePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWinnerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nftTokenId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nop", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;

  events: {};
}

export interface DutchAuctions extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DutchAuctionsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    bid(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    erc20TokenAddress(overrides?: CallOverrides): Promise<[string]>;

    erc721TokenAddress(overrides?: CallOverrides): Promise<[string]>;

    finalize(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getAddressOfOwner(overrides?: CallOverrides): Promise<[string]>;

    getNounceValue(overrides?: CallOverrides): Promise<[BigNumber]>;

    getNumBlocksOpen(overrides?: CallOverrides): Promise<[BigNumber]>;

    getOfferPriceDecrement(overrides?: CallOverrides): Promise<[BigNumber]>;

    getPrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    getReservePrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    getWinnerAddress(overrides?: CallOverrides): Promise<[string]>;

    nftTokenId(overrides?: CallOverrides): Promise<[BigNumber]>;

    nop(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    refund(
      refundAmount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  bid(
    amount: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  erc20TokenAddress(overrides?: CallOverrides): Promise<string>;

  erc721TokenAddress(overrides?: CallOverrides): Promise<string>;

  finalize(
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getAddressOfOwner(overrides?: CallOverrides): Promise<string>;

  getNounceValue(overrides?: CallOverrides): Promise<BigNumber>;

  getNumBlocksOpen(overrides?: CallOverrides): Promise<BigNumber>;

  getOfferPriceDecrement(overrides?: CallOverrides): Promise<BigNumber>;

  getPrice(overrides?: CallOverrides): Promise<BigNumber>;

  getReservePrice(overrides?: CallOverrides): Promise<BigNumber>;

  getWinnerAddress(overrides?: CallOverrides): Promise<string>;

  nftTokenId(overrides?: CallOverrides): Promise<BigNumber>;

  nop(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  refund(
    refundAmount: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    bid(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    erc20TokenAddress(overrides?: CallOverrides): Promise<string>;

    erc721TokenAddress(overrides?: CallOverrides): Promise<string>;

    finalize(overrides?: CallOverrides): Promise<void>;

    getAddressOfOwner(overrides?: CallOverrides): Promise<string>;

    getNounceValue(overrides?: CallOverrides): Promise<BigNumber>;

    getNumBlocksOpen(overrides?: CallOverrides): Promise<BigNumber>;

    getOfferPriceDecrement(overrides?: CallOverrides): Promise<BigNumber>;

    getPrice(overrides?: CallOverrides): Promise<BigNumber>;

    getReservePrice(overrides?: CallOverrides): Promise<BigNumber>;

    getWinnerAddress(overrides?: CallOverrides): Promise<string>;

    nftTokenId(overrides?: CallOverrides): Promise<BigNumber>;

    nop(overrides?: CallOverrides): Promise<boolean>;

    refund(
      refundAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    bid(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    erc20TokenAddress(overrides?: CallOverrides): Promise<BigNumber>;

    erc721TokenAddress(overrides?: CallOverrides): Promise<BigNumber>;

    finalize(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getAddressOfOwner(overrides?: CallOverrides): Promise<BigNumber>;

    getNounceValue(overrides?: CallOverrides): Promise<BigNumber>;

    getNumBlocksOpen(overrides?: CallOverrides): Promise<BigNumber>;

    getOfferPriceDecrement(overrides?: CallOverrides): Promise<BigNumber>;

    getPrice(overrides?: CallOverrides): Promise<BigNumber>;

    getReservePrice(overrides?: CallOverrides): Promise<BigNumber>;

    getWinnerAddress(overrides?: CallOverrides): Promise<BigNumber>;

    nftTokenId(overrides?: CallOverrides): Promise<BigNumber>;

    nop(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    refund(
      refundAmount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    bid(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    erc20TokenAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    erc721TokenAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    finalize(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getAddressOfOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getNounceValue(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getNumBlocksOpen(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getOfferPriceDecrement(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getReservePrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getWinnerAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    nftTokenId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    nop(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    refund(
      refundAmount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
