/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20Sol from "./erc20.sol";
export type { erc20Sol };
export type { DutchAuctions } from "./DutchAuctions";
export type { HuskyToken } from "./HuskyToken";
export type { TransparentUpgradeableProxy } from "./TransparentUpgradeableProxy";
