/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20Sol from "./erc20.sol";
export { DutchAuctions__factory } from "./DutchAuctions__factory";
export { HuskyToken__factory } from "./HuskyToken__factory";
export { TransparentUpgradeableProxy__factory } from "./TransparentUpgradeableProxy__factory";
